old_sound_rabbit_mq:
    connections:
        default:
            host:     'host.docker.internal'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0  
    producers:
        upload_comment:
            class: App\Comment\Infrastructure\CommentPostEndpoint
            connection: default
            queue_options: 
                name: upload_comment
            exchange_options: 
                name: 'upload-comment'
                type: direct