version: '3'

services:    
    web:
      image: nginx
      ports:
        - 8000:80
      depends_on:
        - php
        - comments-adapter 
      volumes:
        - .:/app
        - ./docker-dev/nginx/site.conf:/etc/nginx/conf.d/default.conf

    php:
      image: nikfilias/comments-api
      depends_on: 
        - db
      volumes:
        - .:/app

    comments-adapter:
      image: nikfilias/comments-adapter
      depends_on: 
        - db


    db:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 3307:3306
      
    rabbit-mq:
      image: rabbitmq:3.8-management
      hostname: rabbit-mq
      ports:
        - 8081:15672
        - 5672:5672

      