version: '3'

services:    
    web:
      image: nginx
      ports:
        - 8000:80
      depends_on:
        - php      
      volumes:
        - .:/app
        - ./docker-dev/nginx/site.conf:/etc/nginx/conf.d/default.conf

    php:
      build:
        context: .
        dockerfile: ./docker-dev/Dockerfile
      volumes:
        - .:/app
      depends_on: 
        - db

    db:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 3307:3306

    rabbit-mq:
      image: rabbitmq:3.8
      hostname: rabbit-1
      ports:
        - 8080:15672
      
    rabbit-manager:
      image: rabbitmq:3.8-management
      hostname: rabbit-manager
      ports:
        - 8080:15672
      environment:
        RABBITMQ_ERLANG_COOKIE: HQNXXSZKJVKHGCWEKLZI

      